version: 0.2

phases:
  install:
    commands:
      - echo "Installing AWS CLI..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
  build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync . s3://fwasgsdhtrh232323 --delete
      - echo "Creating CloudFront invalidation..."
      - aws cloudfront create-invalidation --distribution-id E34LOT5PYJB7FD --paths "/*"

artifacts:
  files:
    - '**/*'
