version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync . s3://fwasgsdhtrh232323 --delete

artifacts:
  files:
    - '**/*'
